//	Header generated by Constructor for Pilot 1.0.2

//

//	Generated at 2:42:07 PM on Wednesday, November 4, 1998

//

//	Generated for file: Phantom:Projects:Emulator:main:ROM_Transfer:Resources:ROM Transfer.rsrc

//

//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALMPILOT;

//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST

//

//	Pilot App Name: 		"ROM Transfer"

//

//	Pilot App Version: 		"2.0"







//	Resource: tFRM 1000

#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)

#define MainBeginTransferButton                   1000	//(Left Origin = 79, Top Origin = 138, Width = 74, Height = 16, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)

#define MainInstructionsLabel                     1001	//(Left Origin = 7, Top Origin = 21, Usable = 1, Font = Standard)

#define MainSpeedLabel                            1002	//(Left Origin = 7, Top Origin = 98, Usable = 1, Font = Bold)

#define MainStatusLabel                           1005	//(Left Origin = 49, Top Origin = 114, Usable = 1, Font = Bold)

#define MainStatusTextLabel                       1006	//(Left Origin = 93, Top Origin = 114, Usable = 1, Font = Standard)

#define MainSpeedList                             1004	//(Left Origin = 94, Top Origin = 98, Width = 65, Usable = 0, Font = Standard, Visible Items = 0)

#define MainSpeedPopTrigger                       1003	//(Left Origin = 90, Top Origin = 97, Width = 0, Height = 13, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1004)



